### ISSUE TITLE
TypeError: t.replace is not a function

### ISSUE THREAD

**Issue by soasurs** [vscode-kubernetes-tools/vscode-kubernetes-tools#1215]
After upgrading to v1.3.14, the following issue just occured.

```
2023-09-25 18:38:49.562 [info] ExtensionService#_doActivateExtension ms-kubernetes-tools.vscode-kubernetes-tools, startup: false, activationEvent: 'onView:extension.vsKubernetesExplorer'
2023-09-25 18:38:49.760 [error] Activating extension ms-kubernetes-tools.vscode-kubernetes-tools failed due to an error:
2023-09-25 18:38:49.760 [error] TypeError: t.replace is not a function
	at Object.e [as interpolateVariables] (/home/zzhang/.vscode-server/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-1.3.14/dist/extension.js:32:19239)
	at t.getToolPath (/home/zzhang/.vscode-server/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-1.3.14/dist/extension.js:16:89774)
	at /home/zzhang/.vscode-server/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-1.3.14/dist/extension.js:16:153716
	at Generator.next (<anonymous>)
	at /home/zzhang/.vscode-server/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-1.3.14/dist/extension.js:16:153056
	at new Promise (<anonymous>)
	at r (/home/zzhang/.vscode-server/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-1.3.14/dist/extension.js:16:152801)
	at /home/zzhang/.vscode-server/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-1.3.14/dist/extension.js:16:153622
	at /home/zzhang/.vscode-server/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-1.3.14/dist/extension.js:16:154210
	at Generator.next (<anonymous>)
	at /home/zzhang/.vscode-server/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-1.3.14/dist/extension.js:16:153056
	at new Promise (<anonymous>)
	at r (/home/zzhang/.vscode-server/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-1.3.14/dist/extension.js:16:152801)
	at h (/home/zzhang/.vscode-server/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-1.3.14/dist/extension.js:16:153511)
	at Object.<anonymous> (/home/zzhang/.vscode-server/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-1.3.14/dist/extension.js:16:156155)
	at Generator.next (<anonymous>)
	at /home/zzhang/.vscode-server/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-1.3.14/dist/extension.js:16:153056
	at new Promise (<anonymous>)
	at r (/home/zzhang/.vscode-server/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-1.3.14/dist/extension.js:16:152801)
	at t.invokeForResult (/home/zzhang/.vscode-server/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-1.3.14/dist/extension.js:16:156107)
	at b.<anonymous> (/home/zzhang/.vscode-server/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-1.3.14/dist/extension.js:32:122101)
	at Generator.next (<anonymous>)
	at /home/zzhang/.vscode-server/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-1.3.14/dist/extension.js:32:118691
	at new Promise (<anonymous>)
	at r (/home/zzhang/.vscode-server/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-1.3.14/dist/extension.js:32:118436)
	at b.invokeCommand (/home/zzhang/.vscode-server/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-1.3.14/dist/extension.js:32:122052)
	at b.<anonymous> (/home/zzhang/.vscode-server/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-1.3.14/dist/extension.js:32:123793)
	at Generator.next (<anonymous>)
	at /home/zzhang/.vscode-server/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-1.3.14/dist/extension.js:32:118691
	at new Promise (<anonymous>)
	at r (/home/zzhang/.vscode-server/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-1.3.14/dist/extension.js:32:118436)
	at b.readJSON (/home/zzhang/.vscode-server/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-1.3.14/dist/extension.js:32:123740)
	at /home/zzhang/.vscode-server/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-1.3.14/dist/extension.js:16:106949
	at Generator.next (<anonymous>)
	at /home/zzhang/.vscode-server/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-1.3.14/dist/extension.js:16:106752
	at new Promise (<anonymous>)
	at r (/home/zzhang/.vscode-server/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-1.3.14/dist/extension.js:16:106497)
	at p (/home/zzhang/.vscode-server/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-1.3.14/dist/extension.js:16:106899)
	at Object.<anonymous> (/home/zzhang/.vscode-server/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-1.3.14/dist/extension.js:16:107428)
	at Generator.next (<anonymous>)
	at /home/zzhang/.vscode-server/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-1.3.14/dist/extension.js:16:106752
	at new Promise (<anonymous>)
	at r (/home/zzhang/.vscode-server/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-1.3.14/dist/extension.js:16:106497)
	at Object.h [as currentNamespace] (/home/zzhang/.vscode-server/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-1.3.14/dist/extension.js:16:107380)
	at /home/zzhang/.vscode-server/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-1.3.14/dist/extension.js:24:189132
	at Generator.next (<anonymous>)
	at s (/home/zzhang/.vscode-server/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-1.3.14/dist/extension.js:24:177614)

**Comment by lstocchi** [comment]
Hi @soasurs , could you please copy/paste the value of your `vs-kubernetes.*` and `vscode-kubernetes.*` settings? Specifically those regarding the tools (kubectl, helm, minikube).

**Comment by soasurs** [comment]
Sure.

```
{
  "vscode-kubernetes.kubectl-path.mac": "/opt/homebrew/bin/kubectl",
  "vscode-kubernetes.helm-path.mac": "/opt/homebrew/bin/helm",
  "vscode-kubernetes.minikube-path.mac": "/opt/homebrew/bin/minikube",
  "vs-kubernetes": {
    "vscode-kubernetes.helm-path.linux": "/home/zzhang/.local/state/vs-kubernetes/tools/helm/linux-amd64/helm",
    "vscode-kubernetes.kubectl-path.linux": "/home/zzhang/.local/state/vs-kubernetes/tools/kubectl/kubectl",
    "vscode-kubernetes.minikube-path.linux": "/home/zzhang/.local/state/vs-kubernetes/tools/minikube/linux-amd64/minikube",
    "vs-kubernetes.minikube-show-information-expiration": "2024-01-23T07:56:33.987Z"
  }
}
```

Currently, I code on a MacBook with Remote SSH to a Fedora Linux VM. I just try to solve the problem. When I comment the line `vscode-kubernetes.kubectl-path.mac`, it just works. But I don't understand why `vscode-kubernetes.kubectl-path.mac` will impact the remote extension?

**Comment by lstocchi** [comment]
@soasurs glad you found a way to make it work for the moment. 

I was expecting you to have some `${...}` values as it looks to fail during interpolation and in that phase we only replace strings with that syntax, so i'm a bit puzzled.
The other thing may be related to the active text editor. I'll investigate more about it later.

Do you face the same issue if you work locally without remote ssh?

**Comment by soasurs** [comment]
> @soasurs glad you found a way to make it work for the moment.
> 
> I was expecting you to have some `${...}` values as it looks to fail during interpolation and in that phase we only replace strings with that syntax, so i'm a bit puzzled. The other thing may be related to the active text editor. I'll investigate more about it later.
> 
> Do you face the same issue if you work locally without remote ssh?
> 
> Thanks for your help!!

It looks like everything works well on locally.

**Comment by DC-Ops** [comment]
For me, the issue was with `vscode-kubernetes.kubectl-path.linux` and the issue was very silly! I just had to replace "." with "-"

**Comment by orgads** [comment]
I also hit the same issue. Is it possible to auto-migrate this setting?

**Comment by cj13579** [comment]
I ran into this issue too. I _think_ that my issue was that I had references to the `kubectl-path.windows` and `helm-path.windows` at the root of my settings file. In the end I went a bit overkill but I resolved the issue by:

1. Uninstalling the extension
2. Manually deleted all `vscode-kubernetes*` references that were left in _settings.json_
3. Reinstalled the extension

After the re-installation, it all worked fine.
